### ISSUE TITLE
Docs show outdated compose file compared to what's being generated

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#142]
https://docs.defang.io/docs/tutorials/deploy-code-compose

"Plus, the docs on that page tell me that I will need to make my own Dockerfile and my own compose.yml, however the
generate command already did those. Confusing."

**Comment by lionello** [comment]
That tutorial is the one that tells you how to use compose+Dockerfile. The "generate" tutorial doesn't show any compose/Dockerfile, but its title could be better. Right now it sounds like it only generates, no deployment: "Create an outline using AI"

**Comment by lionello** [comment]
Fixed by 74cddbbbffd6f82d8b3f7a73786430aa4f4f5962 and 47a0d71198390be3b55607ff18ca1e8e1a48d1d8
