### ISSUE TITLE
CLI should prompt user to agree to terms before anything else

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#143]
"Got Error: failed_precondition: you must agree to the latest terms first"

Need to prompt upfront, on first use of the Defang CLI

- [ ] add ToS step to all tutorials "If you haven't already, …"
- [ ] add ability to open browser from CLI
- [ ] create interactive "agree y/n" prompt

**Comment by lionello** [comment]
Instead of exiting with an error, the CLI could handle the error by interactively, opening the browser, and prompting for "agree y/n", proceeding with the actual command, all in one invocation.

**Comment by lionello** [comment]
Partial fix https://github.com/defang-io/defang-docs/commit/126537a14aa212f33a899ae824c62449f798ca33

**Comment by raphaeltm** [comment]
> Instead of exiting with an error, the CLI could handle the error by interactively, opening the browser, and prompting for "agree y/n", proceeding with the actual command, all in one invocation.

That sounds like a good experience.
