### ISSUE TITLE
"defang terms --agree-tos" claims user has agreed even before they have a chance to read TOS and actually agree

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#144]
```
> defang terms --agree-tos
* Connecting to fabric-prod1.defang.dev:443
  Our latest terms of service can be found at https://defang.io/terms-
  service.html
   * You have agreed to the Defang terms of service
```

**Comment by lionello** [comment]
This flag was copied from certbot, https://eff-certbot.readthedocs.io/en/stable/using.html . The better workflow would be the one described in #143 . We could even consider removing the flag.

**Comment by lionello** [comment]
This was partially addressed by https://github.com/defang-io/defang/commit/03a6e3ddc1a6066bdbe257fe2979b984e0601c07, but that made the DX worse by introducing an additional step.

**Comment by lionello** [comment]
Considering this one fixed and closing it. More ToS improvements tracked by #143
