### ISSUE TITLE
Very verbose output even without verbose turned on

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#145]
"For example: 20:52:32.665143 service1 status=SERVICE_STEADY_STATE. What does that even mean?
Also:
1. My URL had scrolled off of the screen thanks to the log spam
2. defang isn't telling me that my service is ready.
3. When I go back, scrolling up to find my URL, it tells me this message: 
Service service1 is in state BUILD_QUEUED and will be available at:
"

**Comment by lionello** [comment]
that particular message should not have been shown with verbose=off. Those status messages are generated by fabric controller in response to ECS task/service events.

**Comment by lionello** [comment]
service status updates are sent to Stdout https://github.com/defang-io/defang-mvp/blob/d7e148bda93aeef28fd34ebdefff726aa1823553/fabric/cmd/server/fabric.go#L535

**Comment by lionello** [comment]
"fabric" wasn't considered an "internal" service, so stdout was still shown
