### ISSUE TITLE
failed_precondition: you must agree to the latest terms first

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#155]
This might be a dup of other bugs we are addressing wrt ToS but logging it just to make sure. This is with latest CLI code from main.

```
Error: failed_precondition: you must agree to the latest terms first

Please use the following command to see the Defang terms of service:

  defang terms
```

**Comment by lionello** [comment]
Regression from https://github.com/defang-io/defang-mvp/pull/519

**Comment by lionello** [comment]
Improvements to ToS DX are tracked by #143
