### ISSUE TITLE
CNAME error message is misleading

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#177]
When using BYOD, you can get this message when first deploying and the domain is not setup:

```
error looking up CNAME "mydomain.com": lookup mydomain.com on [x]: no such host
```

Defang is supposed to be provisioning that record for me, so I'm not sure why it's throwing an error.

**Comment by lionello** [comment]
That error made sense for Playground because we can't make the CNAME record for you. For BYOC we should probably skip it.
