### ISSUE TITLE
Defang CLI development version hash

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#243]
```
➜  src git:(main) defang version
Defang CLI:    development
Latest CLI:    v0.5.7
Defang Fabric: v0.5.0-255-gb763d545
```

That's what I'm seeing when I run `defang version` from a local build.

I find it more informative/useful to know the version hash, than `development`. I thought it used to print the hash?

**Comment by lionello** [comment]
Depends how you built it. If you just do `go build` then nothing will replace the string "development" with the GIT commit ref. If you use the `Makefile`, it will do that for you.
