### ISSUE TITLE
File count warning

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#244]
I pretty regularly get this warning:

```
 ! The build context contains more than 10 files; press Ctrl+C if this is unexpected.
 ```

I think it's unhelpful, though, without the ability to list what files Defang is picking up. Right now, every time I see that I wonder, "huh, it's a small project, I don't know how many files I should expect... I should double check my `.dockerignore` and/or count the files manually." My `.dockerignore` is correct, but I still end up counting my files just in case something weird is going on.

**Suggestions**

* The warning should provide a file count
* There should be a command to list the files defang will pick up i.e. `defang compose files`

**Comment by lionello** [comment]
Adding the `--debug` flag will show the list of files. Showing the actual count means we can't show this warning until the very end, which might be hours away depending on the size of your context (imagine running `compose up` in your root)

**Comment by lionello** [comment]
Warning should provide suggestions, like "check .dockerignore" or "add --debug"

**Comment by raphaeltm** [comment]
@lionello yeah, I like the idea of getting the `--debug` in the warning.

> Showing the actual count means we can't show this warning until the very end, which might be hours away depending on the size of your context

Wouldn't the command fail before that because of the size limit? It still might be useful if, for example, you have a relatively small project, but have some 3rd party packages included that should be downloaded at build time: you might have few enough that it doesn't take very long, but you'll still see that your file is 100 files instead of 20. (I'm not entirely sure I follow re: the timing though, so that might not make sense)
