### ISSUE TITLE
.dev ACME BYOD trigger

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#250]
The current flow for ACME BYOD states:

> access http://<domain> to trigger the certificate issuance

In my case, the domain was access `n.goec.dev`. My instinct was to open it in the browser. But `.dev` domains are required to use SSL, so you cannot open `http://n.goec.dev` in the browser (you automatically get redirected to `https`). 

You _can_, however, access the `http` endpoint using curl, so it might be worth it to just print out the curl command:

> trigger the certificate issuance using `curl http://n.goec.dev`

**Comment by lionello** [comment]
- [ ] add a Defang CLI command to trigger the issuance
