### ISSUE TITLE
suggestion: provide date & time stamps for both portal and tail

### ISSUE THREAD

**Issue by beorn** [defang-io/defang#251]
Hi,

Currently on the portal my logs look like this:
```logs
[DEBUGGER] OUT <– Awareness/Update
url="/" requesting
[DEBUGGER] OUT <– Awareness/Update
url="/" requesting
doc="05434214" disconnecting
url="/" requesting
```

whereas when I do `defang tail` they look like this:
```logs
11:12:01.225163 tn9qf51j0533 decker-app [DEBUGGER] OUT <– Awareness/Update
11:12:32.399175 tn9qf51j0533 decker-app url="/" requesting
11:12:32.914185 tn9qf51j0533 decker-app [DEBUGGER] OUT <– Awareness/Update
11:13:02.417512 tn9qf51j0533 decker-app url="/" requesting
11:13:02.902313 tn9qf51j0533 decker-app doc="05434214" disconnecting
11:13:32.443354 tn9qf51j0533 decker-app url="/" requesting
```

There are two problems:

1. I'd like to have date & time stamps for the logs, but `defang tail` only shows the time
2. I'm not sure if I should add date & time to my logs or rely on Defang's built-in date-time-stamping — I would prefer to rely on the built-in one, but then the portal should also have the date & time and it currently doesn't

**Comment by lionello** [comment]
Closing in favor of https://github.com/defang-io/portal/issues/39
