### ISSUE TITLE
No feedback on some commands if detached from log stream

### ISSUE THREAD

**Issue by nullfunc** [defang-io/defang#256]
Repro:
From command line:
1. deploy a service
2. ctrl-c to detach from log stream
3. issue command '**defang compose restart**'

Result: No response on command line, just new command line prompt shows.
Expected: Some feedback to the user that something occurred. (From another terminal still viewing the log stream the command was handled).

There may be other commands which also do not provide feedback if detached, there should be some sort of message to the user. Something like "operation XZY complete" or "command executed. To view logs enter this 'tail WXZY'".

**Comment by lionello** [comment]
Please investigate which cmds have this problem.

**Comment by nullfunc** [comment]
List of known commands providing no response after command is issued and executing. 
- [ ] defang compose restart - behaviour change now shows "Error: no project found"
- [ ] defang restart service1 - show's error "Error: not_found: service "service1" not found". note "not_found"
- [ ] defang restart <service>
- [ ] defang compose stop
