### ISSUE TITLE
Portal URL on CLI shows for defang.dev deployment when doing defang compose up 

### ISSUE THREAD

**Issue by nullfunc** [defang-io/defang#319]
![Screenshot 2024-04-30 at 3 51 13 PM](https://github.com/defang-io/defang/assets/7478236/1fa84110-e53f-42d9-a965-2e80888d3f73)

The logs show URL for portal even though portal will not show service information for non defang.dev deployments.

**Comment by lionello** [comment]
should probably add a check to ensure we're going to prod fabric? Or we could add the portal URL to the `ServiceInfo` struct that is filled by fabric, and then the CLI simply prints that value iff it's set.
