### ISSUE TITLE
Different secret names between SSM and Task

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#52]
There are different names between the secret in SSM and in what is being loaded during CD. (@lionello)

SSM:
![CleanShot 2024-01-26 at 19 34 40@2x](https://github.com/defang-io/defang/assets/910895/8bec850a-b53d-4706-a036-7daee52f19d2)

CD:
![CleanShot 2024-01-26 at 19 38 41@2x](https://github.com/defang-io/defang/assets/910895/99962b13-2ba8-4d61-a8d3-1a2b0a884030)

**Comment by lionello** [comment]
fixed in 2bcb76c

**Comment by lionello** [comment]
You'll have to recreate your secrets.
