### ISSUE TITLE
Compose Down + Compose Up Results in Silent Failure

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#59]
In one terminal I ran `defang compose down` for "Project A".

In another terminal I ran `defang compose up` for "Project B".

It was taking a while for "Project B" to come up, so I took a look and realized "Project A" was still being torn down. "Project A" never came up, but there was no feedback from the CLI to let me know that it was never going to happen, just the little spinner.

**Comment by lionello** [comment]
This currently fails because `down` returns immediately, even though Pulumi is in progress. Up fails because the current "down" has the stack locked.

**Comment by lionello** [comment]
Fixed by e0826d3c873df3d80aa4be11948a53b4862641c7
