### ISSUE TITLE
It's not clear that 'compose up' has completed. It's still showing a spinner.

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#65]
11:03:55.539000 cd pulumi Resources:
11:03:55.539000 cd pulumi     + 8 created
11:03:55.539000 cd pulumi     66 unchanged
11:03:55.539000 cd pulumi Duration: 1m31s
\

**Comment by lionello** [comment]
Fixed in 2c442da0fc7f82fe54194457ae0a1bd3e34ae44c
