### ISSUE TITLE
 ‘compose down’ not tailing logs til the end

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#66]
2 minor issues with 'compose down':

1) It says “To track the deployment status, do: …”

From the user’s perspective, he’s not doing a deployment, he’s removing things

2) `defang --cluster aws tail --etag a42fe6`
Why does the user need to do this as opposed to just having the command tail automatically like ‘compose up’ does?

[Lio]
1. s/deployment/update/
2. Make down behave like up (and stop behave like start): down shows “cd” logs

**Comment by lionello** [comment]
Done in e0826d3c873df3d80aa4be11948a53b4862641c7
