### ISSUE TITLE
2 warnings showing up with compose up. What should the user do with those?

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#67]
WARNING ingress port without healthcheck defaults to GET / HTTP/1.1
WARNING missing memory reservation; specify deploy.resources.reservations.memory to avoid out-of-memory errors

[Lio]
- Better wording?
- Point to a FAQ https://github.com/defang-io/defang-docs/blob/main/docs/faq.md

**Comment by lionello** [comment]
Fixed by bdb0318f3885fe0a21eed9622983b1a6b350926f
