### ISSUE TITLE
Non-verbose compose up still generating lots of log information

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#69]
11:14:25.079000 kaniko INFO[0000] Resolved base name golang:1.20-alpine to builder
11:14:25.079000 kaniko INFO[0000] Retrieving image manifest golang:1.20-alpine
11:14:25.079000 kaniko INFO[0000] Retrieving image library/golang:1.20-alpine

**Comment by lionello** [comment]
Fixed in 4ae4d7996aced49447c70138153921d04421903a
