### ISSUE TITLE
Non-verbose compose up seems to never finish and doesn’t show the deployment URL

### ISSUE THREAD

**Issue by acote88** [defang-io/defang#70]
11:14:35.353000 kaniko INFO[0010] Pushing image to XXXXXXX
11:14:35.461000 kaniko INFO[0010] Pushed XXXXXXXX
|
\

- [x] non-verbose compose up never finished; duplicate of #65 
- [x] show cloud front URL; addressed by #55 

[Lio]
Possibly fixed by domain delegation
we could still print the cloudfront URL post pulumi up

**Comment by lionello** [comment]
Fixed by #55
