### ISSUE TITLE
Adjust limits in BYOC

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#72]
If I'm using Defang BYOC to deploy to my own cloud accounts, I shouldn't have the same limits as Defang Hosted.

Ideally, there should be UX around setting account-wide limits, or project-based limits get applied at deploy-time. Something like:

```
defang config set --scope=account --key=deploy.resources.reservations.cpus --value=4.0
```

```
defang config set --scope=project --project=application-x --key=deploy.resources.reservations.memory --value=4096
```

**Comment by lionello** [comment]
Done in 82e47e0f6d8f60d4764d53751dbfe6fc8e63c920
